version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASS: "${REDIS_PASS}"
    ports:
      - '8076:80'
    volumes:
      - /srv/docker_data/f76-api/logs:/var/local/F76_API_Server