version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASS: "${REDIS_PASS}"
    ports:
      - '8076:80'
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    name: redis-data
    driver: local
    driver_opts:
      type: bind
      device: /srv/docker_data/
      o: bind